name: Build/release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        run: npm ci && cd hcs_settings && npm ci && cd ..

      - name: Build
        run: npm run compile

      - name: Make tarball
        run: tar -czf homeycommunityspace.tar.gz -C .homeybuild .

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: homeycommunityspace.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write
