name: Build/release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Build
        run: npx homey app build

      - name: Make tarball
        run: tar -czf homeycommunityspace.tar.gz .homeybuild

      - name: Update release
        uses: ColinPitrat/update-release@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./homeycommunityspace.tar.gz
          prerelease: false
          draft: false

    permissions:
      contents: write
